package be.artesis.timelog.gui;

import be.artesis.timelog.controller.Inserter;
import be.artesis.timelog.model.Validator;
import be.artesis.timelog.model.WebserviceException;
import be.artesis.timelog.view.DataInputException;
import be.artesis.timelog.view.Opdrachtgever;
import java.io.IOException;
import java.net.MalformedURLException;
import javax.swing.JOptionPane;
import org.json.JSONException;

/**
 *
 * @author Gilliam
 */
public class NewClientDialog extends javax.swing.JDialog {

    Validator validator;
    Opdrachtgever client = new Opdrachtgever();
    /**
     * Creates new form NewClientDialog
     * @param parent
     * @param modal
     * @param validator
     */
    public NewClientDialog(java.awt.Frame parent, boolean modal, Validator validator) {
        super(parent, modal);
        this.validator = validator;
        setLocationRelativeTo(parent);
        initComponents();

    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newClientJPanel = new javax.swing.JPanel();
        addClientJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        telephoneJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        telephoneJTextField = new javax.swing.JTextField();
        firstNameJLabel = new javax.swing.JLabel();
        companyJTextField = new javax.swing.JTextField();
        emailJLabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        companyJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        newClientJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addClientJButton.setText("Add Client");
        addClientJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientJButtonClicked(evt);
            }
        });

        telephoneJLabel.setText("Telephone number");

        nameJLabel.setText("Name");

        firstNameJLabel.setText("First name");

        emailJLabel.setText("Email adress");

        companyJLabel.setText("Company");

        javax.swing.GroupLayout newClientJPanelLayout = new javax.swing.GroupLayout(newClientJPanel);
        newClientJPanel.setLayout(newClientJPanelLayout);
        newClientJPanelLayout.setHorizontalGroup(
            newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClientJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClientJPanelLayout.createSequentialGroup()
                                .addComponent(telephoneJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(telephoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newClientJPanelLayout.createSequentialGroup()
                                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(companyJLabel)
                                    .addComponent(firstNameJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameJTextField)
                                    .addComponent(companyJTextField)
                                    .addComponent(nameJTextField)))))
                    .addComponent(addClientJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newClientJPanelLayout.createSequentialGroup()
                        .addComponent(emailJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        newClientJPanelLayout.setVerticalGroup(
            newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameJLabel))
                .addGap(18, 18, 18)
                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel))
                .addGap(18, 18, 18)
                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyJLabel))
                .addGap(18, 18, 18)
                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJLabel)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(newClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneJLabel)
                    .addComponent(telephoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addClientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newClientJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newClientJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClientJButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientJButtonClicked
        try {
            addClient();
        } catch (JSONException | WebserviceException | DataInputException | IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        JOptionPane.showMessageDialog(this, "Client added!");
        dispose();
    }//GEN-LAST:event_addClientJButtonClicked

    private void addClient() throws JSONException, MalformedURLException, IOException, WebserviceException, DataInputException {
        client = new Opdrachtgever();
        client.setNaam(nameJTextField.getText());
        client.setVoornaam(firstNameJTextField.getText());
        client.setBedrijfsnaam(companyJTextField.getText());
        client.setEmail(emailJTextField.getText());
        client.setTelefoonnummer(telephoneJTextField.getText());
        client.setID(Inserter.inputOpdrachtgever(validator.getSessionKey(), client)); // Make Client ++ Add ClientID returned from DB
        UserInterface.getUser().addOpdrachtgever(client);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientJButton;
    private javax.swing.JLabel companyJLabel;
    private javax.swing.JTextField companyJTextField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JPanel newClientJPanel;
    private javax.swing.JLabel telephoneJLabel;
    private javax.swing.JTextField telephoneJTextField;
    // End of variables declaration//GEN-END:variables
}