package be.artesis.timelog.gui;

import java.io.IOException;
import java.util.Date;

import javax.swing.JOptionPane;

import org.json.JSONException;

import be.artesis.timelog.clock.Clock;
import be.artesis.timelog.controle.DataControle;
import be.artesis.timelog.controller.Inserter;
import be.artesis.timelog.model.Validator;
import be.artesis.timelog.model.WebserviceException;
import be.artesis.timelog.view.DataInputException;
import be.artesis.timelog.view.Taak;

/**
 * 
 * @author Gilliam
 */
public class NewTaskDialog extends javax.swing.JDialog {
	/**
	 * Creates new form NewTaskDialog
	 * 
	 * @param parent
	 * @param modal
	 */
	Validator validator;

	public NewTaskDialog(java.awt.Frame parent, boolean modal,
			Validator validator) {
		super(parent, modal);
		setLocationRelativeTo(parent);
		initComponents();
		this.validator = validator;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		enddateJTextField = new javax.swing.JTextField();
		startdateJTextField = new javax.swing.JTextField();
		taskNameJTextField = new javax.swing.JTextField();
		enddateJLabel = new javax.swing.JLabel();
		startdateJLabel = new javax.swing.JLabel();
		addTaskJButton = new javax.swing.JButton();
		taskNameJLabel = new javax.swing.JLabel();
		commentJLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		commentJTextArea = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		enddateJTextField.setToolTipText("dd/mm/yyyy");

		startdateJTextField.setToolTipText("dd/mm/yyyy");

		enddateJLabel.setText("End date");

		startdateJLabel.setText("Start date");

		addTaskJButton.setText("Add Task");
		addTaskJButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				addTaskClicked(evt);
			}
		});

		taskNameJLabel.setText("Taskname");

		commentJLabel.setText("Comment");

		commentJTextArea.setColumns(20);
		commentJTextArea.setRows(5);
		jScrollPane1.setViewportView(commentJTextArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		startdateJLabel)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		enddateJLabel)
																.addGap(6, 6, 6))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		startdateJTextField,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		114,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		enddateJTextField))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		taskNameJLabel)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		taskNameJTextField))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						commentJLabel)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										addTaskJButton,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										234,
																										Short.MAX_VALUE)))
																.addGap(0,
																		0,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(taskNameJLabel)
												.addComponent(
														taskNameJTextField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(startdateJLabel)
												.addComponent(enddateJLabel))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														startdateJTextField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														enddateJTextField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(commentJLabel)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										104, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(addTaskJButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										66,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		startdateJTextField.setText(DataControle.sdf.format(new Date()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addTaskClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_addTaskClicked
		try {
			Taak t = new Taak();
			t.setNaam(taskNameJTextField.getText());
			t.setBegindatum(Clock.StringToTimestamp(startdateJTextField
					.getText()));
			t.setGeschatteEinddatum(Clock.StringToTimestamp(enddateJTextField
					.getText()));
			t.setCommentaar(commentJTextArea.getText());
			// Send to Database
			int pid = UserInterface.getCurrentProject().getId();
			System.out.println(pid);
			t.setId((Inserter.inputTaak(validator.getSessionKey(), t, pid)));
			UserInterface.getCurrentProject().addTaak(t);
			JOptionPane.showMessageDialog(this, "Task added!");
			dispose();
		} catch (IOException | WebserviceException | JSONException
				| GUIException | DataInputException ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}// GEN-LAST:event_addTaskClicked
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JButton addTaskJButton;
	private javax.swing.JLabel commentJLabel;
	private javax.swing.JTextArea commentJTextArea;
	private javax.swing.JLabel enddateJLabel;
	private javax.swing.JTextField enddateJTextField;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel startdateJLabel;
	private javax.swing.JTextField startdateJTextField;
	private javax.swing.JLabel taskNameJLabel;
	private javax.swing.JTextField taskNameJTextField;
	// End of variables declaration//GEN-END:variables
}
